# Generated by Django 3.2.12 on 2023-01-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
